# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: registry.gitlab.com/zhangbolily/bthreadpack/build-environment/ubuntu:18.04

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  before_script:
  script:
    - mkdir build && cd build
    - cmake ..
    - make -j 4
    - make install
    # after_script:

# run tests using the binary built before
# test:
  # stage: test
  # script:
