stages:
  - build

linux build:
  tags:
    - linux
  stage: build
  image: registry.gitlab.com/zhangbolily/bthreadpack/build-environment/ubuntu:18.04
  script:
    - mkdir build && cd build
    - cmake ..
    - make -j 4
    - make install

windows build:
  tags:
    - Windows
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j 4
    - make install
