stages:
  - build

linux build:
  tags:
    - linux
  stage: build
  image: registry.gitlab.com/zhangbolily/bthreadpack/build-environment/ubuntu:18.04
  script:
    - mkdir build && cd build
    - cmake ..
    - make -j 4
    - make install
    - bin/GeneralThreadPool_HelloWorld

windows build:
  tags:
    - Windows
  stage: build
  script:
    - mkdir build
    - cd build
    - Remove-Item -Recurse -Force ./*
    - cmake ..  -DWINDOWS_STL_INCLUDE_DIR="C:\\Program Files\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\include" -D CMAKE_C_COMPILER=gcc -D CMAKE_CXX_COMPILER=g++ -G "MinGW Makefiles"
    - make -j 4
    - make install
