linux build:
  stage: build
  tags:
    - Linux
  image: registry.gitlab.com/zhangbolily/bthreadpack/build-environment/ubuntu:18.04
  script:
    - mkdir build && cd build
    - cmake ..
    - make -j 4
    - make install
    # after_script:

window build:
  stage:
    - build
  tags:
    - Windows
  script:
    - mkdir build && cd build
    - cmake ..
    - make -j 4
    - make install

# run tests using the binary built before
# test:
  # stage: test
  # script:
